// Generated by scripts/gen-types.mjs from the same verified OpenAPI.
export const API_COMMIT = '186be7482437eb5dd4b70914843dc6c5f90395f1';
export const API_SCHEMA_SHA256 =
  'fc0e3ee8f02d5bcc11822c14979f9a3f6702d7e8bafb3c0df8fd30b1ac6c5699';
export const IDEMPOTENT_OPERATIONS = [
  'POST /api/v1/billing/subscribe',
  'POST /api/v1/caixa',
  'POST /api/v1/titulares/trocas',
  'POST /api/v1/titulares/trocas/preview',
] as const;
export const UPLOAD_OPERATIONS = [
  'POST /api/v1/apostas/importar-planilha',
  'POST /api/v1/upload',
] as const;
export const PAGINATION_RULES = {
  'GET /api/v1/apostas': {
    page: { default: 1, minimum: 1 },
    page_size: { default: 50, minimum: 1, maximum: 100 },
  },
  'GET /api/v1/caixa': {
    page: { default: 1, minimum: 1, maximum: 9007199254740991 },
    page_size: { default: 50, minimum: 1, maximum: 100 },
  },
  'GET /api/v1/caixa/extrato': {
    page: { default: 1, minimum: 1, maximum: 9007199254740991 },
    page_size: { default: 50, minimum: 1, maximum: 100 },
  },
  'GET /api/v1/revisao': {
    page: { default: 1, minimum: 1, maximum: 9007199254740991 },
    page_size: { default: 50, minimum: 1, maximum: 100 },
  },
  'GET /api/v1/titulares': {
    page: { default: 1, minimum: 1 },
    page_size: { default: 50, minimum: 1, maximum: 100 },
  },
} as const;
