// Generated by scripts/gen-types.mjs from the same verified OpenAPI.
export const API_COMMIT = 'b916f54331f14cf47a3800324bd61d8638043c06';
export const API_SCHEMA_SHA256 =
  '0714381b9e0e4797000932636ffb770b794dc7b6731c1bfcea3d46881bfbe11a';
export const IDEMPOTENT_OPERATIONS = [
  'POST /api/v1/billing/subscribe',
  'POST /api/v1/caixa',
  'POST /api/v1/titulares/trocas',
  'POST /api/v1/titulares/trocas/preview',
] as const;
export const UPLOAD_OPERATIONS = [
  'POST /api/v1/apostas/importar-planilha',
  'POST /api/v1/upload',
] as const;
export const PAGINATION_RULES = {
  'GET /api/v1/apostas': {
    page: { default: 1, minimum: 1 },
    page_size: { default: 50, minimum: 1, maximum: 100 },
  },
  'GET /api/v1/caixa': {
    page: { default: 1, minimum: 1, maximum: 9007199254740991 },
    page_size: { default: 50, minimum: 1, maximum: 100 },
  },
  'GET /api/v1/caixa/extrato': {
    page: { default: 1, minimum: 1, maximum: 9007199254740991 },
    page_size: { default: 50, minimum: 1, maximum: 100 },
  },
  'GET /api/v1/revisao': {
    page: { default: 1, minimum: 1, maximum: 9007199254740991 },
    page_size: { default: 50, minimum: 1, maximum: 100 },
  },
  'GET /api/v1/titulares': {
    page: { default: 1, minimum: 1 },
    page_size: { default: 50, minimum: 1, maximum: 100 },
  },
} as const;
