// Generated by scripts/gen-types.mjs from the same verified OpenAPI.
export const API_COMMIT = '9b42a3579518a84d348d272afbaeff88f9119825';
export const API_SCHEMA_SHA256 =
  'ed837f9a47ea15e839c543412f9aee2bd9a90332ae0a54936c95235c6d432bd5';
export const IDEMPOTENT_OPERATIONS = [
  'POST /api/v1/billing/subscribe',
  'POST /api/v1/caixa',
  'POST /api/v1/titulares/trocas',
  'POST /api/v1/titulares/trocas/preview',
] as const;
export const UPLOAD_OPERATIONS = [
  'POST /api/v1/apostas/importar-planilha',
  'POST /api/v1/upload',
] as const;
export const PAGINATION_RULES = {
  'GET /api/v1/apostas': {
    page: { default: 1, minimum: 1 },
    page_size: { default: 50, minimum: 1, maximum: 100 },
  },
  'GET /api/v1/caixa': {
    page: { default: 1, minimum: 1, maximum: 9007199254740991 },
    page_size: { default: 50, minimum: 1, maximum: 100 },
  },
  'GET /api/v1/caixa/extrato': {
    page: { default: 1, minimum: 1, maximum: 9007199254740991 },
    page_size: { default: 50, minimum: 1, maximum: 100 },
  },
  'GET /api/v1/filtros/{dimensao}': {
    page: { default: 1, minimum: 1 },
    page_size: { default: 50, minimum: 1, maximum: 100 },
  },
  'GET /api/v1/revisao': {
    page: { default: 1, minimum: 1, maximum: 9007199254740991 },
    page_size: { default: 50, minimum: 1, maximum: 100 },
  },
  'GET /api/v1/titulares': {
    page: { default: 1, minimum: 1 },
    page_size: { default: 50, minimum: 1, maximum: 100 },
  },
} as const;
