// Generated from the same verified OpenAPI; unavailable routes stay absent.
export const SITE_READ_CONTRACT = {
  '/api/v1/apostas': {
    query: {
      desde: { anyOf: [{ type: 'string' }, { type: 'null' }] },
      ate: { anyOf: [{ type: 'string' }, { type: 'null' }] },
      estado: { anyOf: [{ type: 'string' }, { type: 'null' }] },
      casa_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
      titular_id: {
        anyOf: [{ type: 'integer', minimum: 1 }, { type: 'null' }],
      },
      conta_casa_id: {
        anyOf: [{ type: 'integer', minimum: 1 }, { type: 'null' }],
      },
      tipster_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
      mercado_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
      competicao_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
      origem: { anyOf: [{ type: 'string' }, { type: 'null' }] },
      revisao_grave: { anyOf: [{ type: 'boolean' }, { type: 'null' }] },
      incluir_apagadas: { type: 'boolean' },
      page: { type: 'integer', minimum: 1 },
      page_size: { type: 'integer', minimum: 1, maximum: 100 },
    },
    response: {
      type: 'object',
      required: ['data', 'pagination'],
      properties: {
        data: {
          type: 'array',
          items: {
            type: 'object',
            required: [
              'chave',
              'origem',
              'estado',
              'odd',
              'stake_unidades',
              'stake_centavos',
              'valor_aposta_centavos',
              'retorno_centavos',
              'lucro_centavos',
              'freebet',
              'conta_casa_id',
              'tipster_id',
              'time_casa_id',
              'time_fora_id',
              'mercado_id',
              'competicao_id',
              'data_aposta',
              'data_jogo',
              'chat_id',
              'message_id',
              'midia_hash',
              'revisao_grave',
              'apagada',
              'casa',
              'evento',
              'descricao',
              'mercado',
              'criada_em',
              'atualizada_em',
            ],
            properties: {
              apagada: { type: 'boolean' },
              atualizada_em: { anyOf: [{ type: 'string' }, { type: 'null' }] },
              banca_contexto: {
                anyOf: [
                  {
                    type: 'object',
                    required: ['id', 'nome'],
                    properties: {
                      id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                      nome: { type: 'string' },
                    },
                  },
                  { type: 'null' },
                ],
              },
              casa: { anyOf: [{ type: 'string' }, { type: 'null' }] },
              chat_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
              chave: { type: 'string' },
              competicao_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
              conta_atribuicao: {
                type: 'string',
                enum: ['ASSIGNED', 'UNASSIGNED'],
              },
              conta_casa_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
              conta_contexto: {
                anyOf: [
                  {
                    type: 'object',
                    required: [
                      'id',
                      'casa_id',
                      'apelido',
                      'ativa',
                      'estado',
                      'titular',
                    ],
                    properties: {
                      apelido: {
                        anyOf: [{ type: 'string' }, { type: 'null' }],
                      },
                      ativa: { type: 'boolean' },
                      casa_id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                      estado: { type: 'string' },
                      id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                      titular: {
                        anyOf: [
                          {
                            type: 'object',
                            required: ['id', 'nome', 'arquivado'],
                            properties: {
                              arquivado: { type: 'boolean' },
                              id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                              nome: { type: 'string' },
                            },
                          },
                          { type: 'null' },
                        ],
                      },
                    },
                  },
                  { type: 'null' },
                ],
              },
              criada_em: { anyOf: [{ type: 'string' }, { type: 'null' }] },
              data_aposta: { anyOf: [{ type: 'string' }, { type: 'null' }] },
              data_jogo: { anyOf: [{ type: 'string' }, { type: 'null' }] },
              descricao: { anyOf: [{ type: 'string' }, { type: 'null' }] },
              estado: { type: 'string' },
              evento: { anyOf: [{ type: 'string' }, { type: 'null' }] },
              freebet: { type: 'boolean' },
              lucro_centavos: {
                anyOf: [{ type: 'integer' }, { type: 'null' }],
              },
              mercado: { anyOf: [{ type: 'string' }, { type: 'null' }] },
              mercado_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
              message_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
              midia_hash: { anyOf: [{ type: 'string' }, { type: 'null' }] },
              odd: { anyOf: [{ type: 'number' }, { type: 'null' }] },
              origem: { type: 'string' },
              retorno_centavos: {
                anyOf: [{ type: 'integer' }, { type: 'null' }],
              },
              revisao_grave: { type: 'boolean' },
              stake_centavos: { type: 'integer' },
              stake_unidades: { type: 'number' },
              time_casa_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
              time_fora_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
              tipster_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
              valor_aposta_centavos: { type: 'integer' },
            },
          },
        },
        pagination: {
          type: 'object',
          required: ['page', 'page_size', 'total'],
          properties: {
            page: { type: 'integer', minimum: 1 },
            page_size: { type: 'integer', minimum: 1 },
            total: { type: 'integer', minimum: 0 },
          },
        },
      },
    },
  },
  '/api/v1/apostas/{chave}': {
    query: {},
    response: {
      type: 'object',
      required: ['aposta', 'selecoes', 'eventos', 'revisao_pendente'],
      properties: {
        aposta: {
          type: 'object',
          required: [
            'chave',
            'origem',
            'estado',
            'odd',
            'stake_unidades',
            'stake_centavos',
            'valor_aposta_centavos',
            'retorno_centavos',
            'lucro_centavos',
            'freebet',
            'conta_casa_id',
            'tipster_id',
            'time_casa_id',
            'time_fora_id',
            'mercado_id',
            'competicao_id',
            'data_aposta',
            'data_jogo',
            'chat_id',
            'message_id',
            'midia_hash',
            'revisao_grave',
            'apagada',
            'casa',
            'evento',
            'descricao',
            'mercado',
            'criada_em',
            'atualizada_em',
          ],
          properties: {
            apagada: { type: 'boolean' },
            atualizada_em: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            banca_contexto: {
              anyOf: [
                {
                  type: 'object',
                  required: ['id', 'nome'],
                  properties: {
                    id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                    nome: { type: 'string' },
                  },
                },
                { type: 'null' },
              ],
            },
            casa: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            chat_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            chave: { type: 'string' },
            competicao_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            conta_atribuicao: {
              type: 'string',
              enum: ['ASSIGNED', 'UNASSIGNED'],
            },
            conta_casa_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            conta_contexto: {
              anyOf: [
                {
                  type: 'object',
                  required: [
                    'id',
                    'casa_id',
                    'apelido',
                    'ativa',
                    'estado',
                    'titular',
                  ],
                  properties: {
                    apelido: { anyOf: [{ type: 'string' }, { type: 'null' }] },
                    ativa: { type: 'boolean' },
                    casa_id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                    estado: { type: 'string' },
                    id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                    titular: {
                      anyOf: [
                        {
                          type: 'object',
                          required: ['id', 'nome', 'arquivado'],
                          properties: {
                            arquivado: { type: 'boolean' },
                            id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                            nome: { type: 'string' },
                          },
                        },
                        { type: 'null' },
                      ],
                    },
                  },
                },
                { type: 'null' },
              ],
            },
            criada_em: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            data_aposta: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            data_jogo: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            descricao: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            estado: { type: 'string' },
            evento: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            freebet: { type: 'boolean' },
            lucro_centavos: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            mercado: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            mercado_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            message_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            midia_hash: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            odd: { anyOf: [{ type: 'number' }, { type: 'null' }] },
            origem: { type: 'string' },
            retorno_centavos: {
              anyOf: [{ type: 'integer' }, { type: 'null' }],
            },
            revisao_grave: { type: 'boolean' },
            stake_centavos: { type: 'integer' },
            stake_unidades: { type: 'number' },
            time_casa_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            time_fora_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            tipster_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            valor_aposta_centavos: { type: 'integer' },
          },
        },
        consolidacoes: { type: 'array', items: { type: 'object' } },
        eventos: {
          type: 'array',
          items: {
            type: 'object',
            required: ['tipo', 'fonte', 'payload', 'confianca', 'criado_em'],
            properties: {
              confianca: { anyOf: [{ type: 'number' }, { type: 'null' }] },
              criado_em: { anyOf: [{ type: 'string' }, { type: 'null' }] },
              fonte: { type: 'string' },
              payload: { type: 'object' },
              tipo: { type: 'string' },
            },
          },
        },
        fonte_contextual: { type: 'boolean' },
        revisao_pendente: {
          anyOf: [
            {
              type: 'object',
              required: ['id', 'motivo', 'midia_hash', 'criado_em'],
              properties: {
                criado_em: { anyOf: [{ type: 'string' }, { type: 'null' }] },
                id: { type: 'integer' },
                midia_hash: { anyOf: [{ type: 'string' }, { type: 'null' }] },
                motivo: { type: 'string' },
              },
            },
            { type: 'null' },
          ],
        },
        selecoes: {
          type: 'object',
          required: ['descricao', 'mercado', 'evento', 'casa'],
          properties: {
            casa: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            descricao: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            evento: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            mercado: { anyOf: [{ type: 'string' }, { type: 'null' }] },
          },
        },
      },
    },
  },
  '/api/v1/revisao/{revisao_id}': {
    query: {},
    response: {
      type: 'object',
      required: [
        'id',
        'midia_hash',
        'motivo',
        'extracao_bruta',
        'criado_em',
        'resolvido_em',
        'foto_url',
      ],
      properties: {
        criado_em: { type: 'string' },
        extracao_bruta: { anyOf: [{ type: 'object' }, { type: 'null' }] },
        foto_url: { anyOf: [{ type: 'string' }, { type: 'null' }] },
        id: { type: 'integer' },
        midia_hash: { anyOf: [{ type: 'string' }, { type: 'null' }] },
        motivo: { type: 'string' },
        resolvido_em: { anyOf: [{ type: 'string' }, { type: 'null' }] },
      },
    },
  },
  '/api/v1/titulares': {
    query: {
      search: { anyOf: [{ type: 'string', maxLength: 160 }, { type: 'null' }] },
      include_archived: { type: 'boolean' },
      page: { type: 'integer', minimum: 1 },
      page_size: { type: 'integer', minimum: 1, maximum: 100 },
    },
    response: {
      type: 'object',
      required: ['data', 'page', 'page_size', 'total'],
      properties: {
        data: {
          type: 'array',
          items: {
            type: 'object',
            required: ['id', 'nome', 'arquivado', 'criado_em'],
            properties: {
              arquivado: { type: 'boolean' },
              criado_em: { type: 'string' },
              id: { type: 'integer' },
              nome: { type: 'string' },
            },
          },
        },
        page: { type: 'integer' },
        page_size: { type: 'integer' },
        total: { type: 'integer' },
      },
    },
  },
  '/api/v1/titulares/{titular_id}/matriz': {
    query: {},
    response: {
      type: 'object',
      required: ['titular', 'contas'],
      properties: {
        contas: {
          type: 'array',
          items: {
            type: 'object',
            required: [
              'conta_casa_id',
              'titular_id',
              'titular_nome',
              'casa_id',
              'casa_nome',
              'apelido',
              'estado',
              'ativa',
              'intervalo_ativo',
              'historico_uso',
              'acoes_validas',
            ],
            properties: {
              acoes_validas: {
                type: 'array',
                items: {
                  type: 'string',
                  enum: ['ATIVAR', 'TROCAR_PARA', 'TROCAR_DE', 'EDITAR'],
                },
              },
              apelido: { type: 'string' },
              ativa: { type: 'boolean' },
              casa_id: { type: 'integer' },
              casa_nome: { type: 'string' },
              conta_casa_id: { type: 'integer' },
              estado: {
                type: 'string',
                enum: ['DISPONIVEL', 'EM_USO', 'LIMITADA', 'ENCERRADA'],
              },
              historico_uso: {
                type: 'array',
                items: {
                  type: 'object',
                  required: ['vigente_de', 'vigente_ate', 'origem'],
                  properties: {
                    origem: { type: 'string', enum: ['LEGADO', 'EXPLICITA'] },
                    vigente_ate: {
                      anyOf: [{ type: 'string' }, { type: 'null' }],
                    },
                    vigente_de: {
                      anyOf: [{ type: 'string' }, { type: 'null' }],
                    },
                  },
                },
              },
              intervalo_ativo: {
                anyOf: [
                  {
                    type: 'object',
                    required: ['vigente_de', 'vigente_ate', 'origem'],
                    properties: {
                      origem: { type: 'string', enum: ['LEGADO', 'EXPLICITA'] },
                      vigente_ate: {
                        anyOf: [{ type: 'string' }, { type: 'null' }],
                      },
                      vigente_de: {
                        anyOf: [{ type: 'string' }, { type: 'null' }],
                      },
                    },
                  },
                  { type: 'null' },
                ],
              },
              titular_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
              titular_nome: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            },
          },
        },
        titular: {
          type: 'object',
          required: ['id', 'nome', 'arquivado', 'criado_em'],
          properties: {
            arquivado: { type: 'boolean' },
            criado_em: { type: 'string' },
            id: { type: 'integer' },
            nome: { type: 'string' },
          },
        },
      },
    },
  },
  'PATCH /api/v1/apostas/{chave}': {
    query: {},
    response: {
      type: 'object',
      required: ['aposta', 'eventos_gravados'],
      properties: {
        aposta: {
          type: 'object',
          required: [
            'chave',
            'origem',
            'estado',
            'odd',
            'stake_unidades',
            'stake_centavos',
            'valor_aposta_centavos',
            'retorno_centavos',
            'lucro_centavos',
            'freebet',
            'conta_casa_id',
            'tipster_id',
            'time_casa_id',
            'time_fora_id',
            'mercado_id',
            'competicao_id',
            'data_aposta',
            'data_jogo',
            'chat_id',
            'message_id',
            'midia_hash',
            'revisao_grave',
            'apagada',
            'casa',
            'evento',
            'descricao',
            'mercado',
            'criada_em',
            'atualizada_em',
          ],
          properties: {
            apagada: { type: 'boolean' },
            atualizada_em: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            banca_contexto: {
              anyOf: [
                {
                  type: 'object',
                  required: ['id', 'nome'],
                  properties: {
                    id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                    nome: { type: 'string' },
                  },
                },
                { type: 'null' },
              ],
            },
            casa: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            chat_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            chave: { type: 'string' },
            competicao_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            conta_atribuicao: {
              type: 'string',
              enum: ['ASSIGNED', 'UNASSIGNED'],
            },
            conta_casa_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            conta_contexto: {
              anyOf: [
                {
                  type: 'object',
                  required: [
                    'id',
                    'casa_id',
                    'apelido',
                    'ativa',
                    'estado',
                    'titular',
                  ],
                  properties: {
                    apelido: { anyOf: [{ type: 'string' }, { type: 'null' }] },
                    ativa: { type: 'boolean' },
                    casa_id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                    estado: { type: 'string' },
                    id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                    titular: {
                      anyOf: [
                        {
                          type: 'object',
                          required: ['id', 'nome', 'arquivado'],
                          properties: {
                            arquivado: { type: 'boolean' },
                            id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                            nome: { type: 'string' },
                          },
                        },
                        { type: 'null' },
                      ],
                    },
                  },
                },
                { type: 'null' },
              ],
            },
            criada_em: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            data_aposta: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            data_jogo: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            descricao: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            estado: { type: 'string' },
            evento: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            freebet: { type: 'boolean' },
            lucro_centavos: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            mercado: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            mercado_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            message_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            midia_hash: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            odd: { anyOf: [{ type: 'number' }, { type: 'null' }] },
            origem: { type: 'string' },
            retorno_centavos: {
              anyOf: [{ type: 'integer' }, { type: 'null' }],
            },
            revisao_grave: { type: 'boolean' },
            stake_centavos: { type: 'integer' },
            stake_unidades: { type: 'number' },
            time_casa_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            time_fora_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            tipster_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            valor_aposta_centavos: { type: 'integer' },
          },
        },
        eventos_gravados: { type: 'integer', minimum: 0 },
      },
    },
  },
  'DELETE /api/v1/apostas/{chave}': {
    query: {},
    response: {
      type: 'object',
      required: ['aposta', 'eventos_gravados'],
      properties: {
        aposta: {
          type: 'object',
          required: [
            'chave',
            'origem',
            'estado',
            'odd',
            'stake_unidades',
            'stake_centavos',
            'valor_aposta_centavos',
            'retorno_centavos',
            'lucro_centavos',
            'freebet',
            'conta_casa_id',
            'tipster_id',
            'time_casa_id',
            'time_fora_id',
            'mercado_id',
            'competicao_id',
            'data_aposta',
            'data_jogo',
            'chat_id',
            'message_id',
            'midia_hash',
            'revisao_grave',
            'apagada',
            'casa',
            'evento',
            'descricao',
            'mercado',
            'criada_em',
            'atualizada_em',
          ],
          properties: {
            apagada: { type: 'boolean' },
            atualizada_em: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            banca_contexto: {
              anyOf: [
                {
                  type: 'object',
                  required: ['id', 'nome'],
                  properties: {
                    id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                    nome: { type: 'string' },
                  },
                },
                { type: 'null' },
              ],
            },
            casa: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            chat_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            chave: { type: 'string' },
            competicao_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            conta_atribuicao: {
              type: 'string',
              enum: ['ASSIGNED', 'UNASSIGNED'],
            },
            conta_casa_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            conta_contexto: {
              anyOf: [
                {
                  type: 'object',
                  required: [
                    'id',
                    'casa_id',
                    'apelido',
                    'ativa',
                    'estado',
                    'titular',
                  ],
                  properties: {
                    apelido: { anyOf: [{ type: 'string' }, { type: 'null' }] },
                    ativa: { type: 'boolean' },
                    casa_id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                    estado: { type: 'string' },
                    id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                    titular: {
                      anyOf: [
                        {
                          type: 'object',
                          required: ['id', 'nome', 'arquivado'],
                          properties: {
                            arquivado: { type: 'boolean' },
                            id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                            nome: { type: 'string' },
                          },
                        },
                        { type: 'null' },
                      ],
                    },
                  },
                },
                { type: 'null' },
              ],
            },
            criada_em: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            data_aposta: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            data_jogo: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            descricao: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            estado: { type: 'string' },
            evento: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            freebet: { type: 'boolean' },
            lucro_centavos: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            mercado: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            mercado_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            message_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            midia_hash: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            odd: { anyOf: [{ type: 'number' }, { type: 'null' }] },
            origem: { type: 'string' },
            retorno_centavos: {
              anyOf: [{ type: 'integer' }, { type: 'null' }],
            },
            revisao_grave: { type: 'boolean' },
            stake_centavos: { type: 'integer' },
            stake_unidades: { type: 'number' },
            time_casa_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            time_fora_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            tipster_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            valor_aposta_centavos: { type: 'integer' },
          },
        },
        eventos_gravados: { type: 'integer', minimum: 0 },
      },
    },
  },
  'POST /api/v1/apostas/{chave}/restaurar': {
    query: {},
    response: {
      type: 'object',
      required: ['aposta', 'eventos_gravados'],
      properties: {
        aposta: {
          type: 'object',
          required: [
            'chave',
            'origem',
            'estado',
            'odd',
            'stake_unidades',
            'stake_centavos',
            'valor_aposta_centavos',
            'retorno_centavos',
            'lucro_centavos',
            'freebet',
            'conta_casa_id',
            'tipster_id',
            'time_casa_id',
            'time_fora_id',
            'mercado_id',
            'competicao_id',
            'data_aposta',
            'data_jogo',
            'chat_id',
            'message_id',
            'midia_hash',
            'revisao_grave',
            'apagada',
            'casa',
            'evento',
            'descricao',
            'mercado',
            'criada_em',
            'atualizada_em',
          ],
          properties: {
            apagada: { type: 'boolean' },
            atualizada_em: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            banca_contexto: {
              anyOf: [
                {
                  type: 'object',
                  required: ['id', 'nome'],
                  properties: {
                    id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                    nome: { type: 'string' },
                  },
                },
                { type: 'null' },
              ],
            },
            casa: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            chat_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            chave: { type: 'string' },
            competicao_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            conta_atribuicao: {
              type: 'string',
              enum: ['ASSIGNED', 'UNASSIGNED'],
            },
            conta_casa_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            conta_contexto: {
              anyOf: [
                {
                  type: 'object',
                  required: [
                    'id',
                    'casa_id',
                    'apelido',
                    'ativa',
                    'estado',
                    'titular',
                  ],
                  properties: {
                    apelido: { anyOf: [{ type: 'string' }, { type: 'null' }] },
                    ativa: { type: 'boolean' },
                    casa_id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                    estado: { type: 'string' },
                    id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                    titular: {
                      anyOf: [
                        {
                          type: 'object',
                          required: ['id', 'nome', 'arquivado'],
                          properties: {
                            arquivado: { type: 'boolean' },
                            id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                            nome: { type: 'string' },
                          },
                        },
                        { type: 'null' },
                      ],
                    },
                  },
                },
                { type: 'null' },
              ],
            },
            criada_em: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            data_aposta: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            data_jogo: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            descricao: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            estado: { type: 'string' },
            evento: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            freebet: { type: 'boolean' },
            lucro_centavos: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            mercado: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            mercado_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            message_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            midia_hash: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            odd: { anyOf: [{ type: 'number' }, { type: 'null' }] },
            origem: { type: 'string' },
            retorno_centavos: {
              anyOf: [{ type: 'integer' }, { type: 'null' }],
            },
            revisao_grave: { type: 'boolean' },
            stake_centavos: { type: 'integer' },
            stake_unidades: { type: 'number' },
            time_casa_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            time_fora_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            tipster_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            valor_aposta_centavos: { type: 'integer' },
          },
        },
        eventos_gravados: { type: 'integer', minimum: 0 },
      },
    },
  },
  'POST /api/v1/apostas/{chave}/resultado': {
    query: {},
    response: {
      type: 'object',
      required: ['aposta', 'eventos_gravados'],
      properties: {
        aposta: {
          type: 'object',
          required: [
            'chave',
            'origem',
            'estado',
            'odd',
            'stake_unidades',
            'stake_centavos',
            'valor_aposta_centavos',
            'retorno_centavos',
            'lucro_centavos',
            'freebet',
            'conta_casa_id',
            'tipster_id',
            'time_casa_id',
            'time_fora_id',
            'mercado_id',
            'competicao_id',
            'data_aposta',
            'data_jogo',
            'chat_id',
            'message_id',
            'midia_hash',
            'revisao_grave',
            'apagada',
            'casa',
            'evento',
            'descricao',
            'mercado',
            'criada_em',
            'atualizada_em',
          ],
          properties: {
            apagada: { type: 'boolean' },
            atualizada_em: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            banca_contexto: {
              anyOf: [
                {
                  type: 'object',
                  required: ['id', 'nome'],
                  properties: {
                    id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                    nome: { type: 'string' },
                  },
                },
                { type: 'null' },
              ],
            },
            casa: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            chat_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            chave: { type: 'string' },
            competicao_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            conta_atribuicao: {
              type: 'string',
              enum: ['ASSIGNED', 'UNASSIGNED'],
            },
            conta_casa_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            conta_contexto: {
              anyOf: [
                {
                  type: 'object',
                  required: [
                    'id',
                    'casa_id',
                    'apelido',
                    'ativa',
                    'estado',
                    'titular',
                  ],
                  properties: {
                    apelido: { anyOf: [{ type: 'string' }, { type: 'null' }] },
                    ativa: { type: 'boolean' },
                    casa_id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                    estado: { type: 'string' },
                    id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                    titular: {
                      anyOf: [
                        {
                          type: 'object',
                          required: ['id', 'nome', 'arquivado'],
                          properties: {
                            arquivado: { type: 'boolean' },
                            id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                            nome: { type: 'string' },
                          },
                        },
                        { type: 'null' },
                      ],
                    },
                  },
                },
                { type: 'null' },
              ],
            },
            criada_em: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            data_aposta: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            data_jogo: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            descricao: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            estado: { type: 'string' },
            evento: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            freebet: { type: 'boolean' },
            lucro_centavos: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            mercado: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            mercado_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            message_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            midia_hash: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            odd: { anyOf: [{ type: 'number' }, { type: 'null' }] },
            origem: { type: 'string' },
            retorno_centavos: {
              anyOf: [{ type: 'integer' }, { type: 'null' }],
            },
            revisao_grave: { type: 'boolean' },
            stake_centavos: { type: 'integer' },
            stake_unidades: { type: 'number' },
            time_casa_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            time_fora_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            tipster_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            valor_aposta_centavos: { type: 'integer' },
          },
        },
        eventos_gravados: { type: 'integer', minimum: 0 },
      },
    },
  },
  'POST /api/v1/revisao/{revisao_id}/resolver': {
    query: {},
    response: {
      type: 'object',
      required: ['revisao', 'acao', 'aposta', 'eventos_gravados'],
      properties: {
        acao: { type: 'string', enum: ['CORRIGIR', 'DESCARTAR', 'MESMA'] },
        aposta: {
          type: 'object',
          required: [
            'chave',
            'origem',
            'estado',
            'odd',
            'stake_unidades',
            'stake_centavos',
            'valor_aposta_centavos',
            'retorno_centavos',
            'lucro_centavos',
            'freebet',
            'conta_casa_id',
            'tipster_id',
            'time_casa_id',
            'time_fora_id',
            'mercado_id',
            'competicao_id',
            'data_aposta',
            'data_jogo',
            'chat_id',
            'message_id',
            'midia_hash',
            'revisao_grave',
            'apagada',
            'casa',
            'evento',
            'descricao',
            'mercado',
            'criada_em',
            'atualizada_em',
          ],
          properties: {
            apagada: { type: 'boolean' },
            atualizada_em: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            banca_contexto: {
              anyOf: [
                {
                  type: 'object',
                  required: ['id', 'nome'],
                  properties: {
                    id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                    nome: { type: 'string' },
                  },
                },
                { type: 'null' },
              ],
            },
            casa: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            chat_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            chave: { type: 'string' },
            competicao_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            conta_atribuicao: {
              type: 'string',
              enum: ['ASSIGNED', 'UNASSIGNED'],
            },
            conta_casa_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            conta_contexto: {
              anyOf: [
                {
                  type: 'object',
                  required: [
                    'id',
                    'casa_id',
                    'apelido',
                    'ativa',
                    'estado',
                    'titular',
                  ],
                  properties: {
                    apelido: { anyOf: [{ type: 'string' }, { type: 'null' }] },
                    ativa: { type: 'boolean' },
                    casa_id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                    estado: { type: 'string' },
                    id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                    titular: {
                      anyOf: [
                        {
                          type: 'object',
                          required: ['id', 'nome', 'arquivado'],
                          properties: {
                            arquivado: { type: 'boolean' },
                            id: { type: 'string', pattern: '^[1-9][0-9]*$' },
                            nome: { type: 'string' },
                          },
                        },
                        { type: 'null' },
                      ],
                    },
                  },
                },
                { type: 'null' },
              ],
            },
            criada_em: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            data_aposta: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            data_jogo: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            descricao: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            estado: { type: 'string' },
            evento: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            freebet: { type: 'boolean' },
            lucro_centavos: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            mercado: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            mercado_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            message_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            midia_hash: { anyOf: [{ type: 'string' }, { type: 'null' }] },
            odd: { anyOf: [{ type: 'number' }, { type: 'null' }] },
            origem: { type: 'string' },
            retorno_centavos: {
              anyOf: [{ type: 'integer' }, { type: 'null' }],
            },
            revisao_grave: { type: 'boolean' },
            stake_centavos: { type: 'integer' },
            stake_unidades: { type: 'number' },
            time_casa_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            time_fora_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            tipster_id: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
            valor_aposta_centavos: { type: 'integer' },
          },
        },
        eventos_gravados: { type: 'integer' },
        revisao: {
          type: 'object',
          required: ['id', 'resolvido_em'],
          properties: {
            id: { type: 'integer' },
            resolvido_em: { type: 'string' },
          },
        },
      },
    },
  },
} as const;
