import { mkdir, readFile, writeFile } from 'node:fs/promises';
import openapiTS, { astToString } from 'openapi-typescript';
import { format, resolveConfig } from 'prettier';
import {
  contractSource,
  operationPolicies,
  verifiedSchema,
} from './api-contract.mjs';

try {
  const pin = JSON.parse(await readFile('config/api-contract.json', 'utf8'));
  const source = contractSource(pin);
  const local = process.argv[2];
  if (local && /^https?:\/\//.test(local)) {
    throw new Error(
      'URLs alternativas não são permitidas. Atualize a referência pinada em revisão.',
    );
  }
  let bytes;
  if (local) bytes = await readFile(local);
  else {
    const response = await fetch(source, {
      signal: AbortSignal.timeout(30_000),
      redirect: 'error',
    });
    if (!response.ok)
      throw new Error('A fonte OpenAPI pinada está indisponível.');
    bytes = Buffer.from(await response.arrayBuffer());
  }
  const document = verifiedSchema(pin, bytes);
  const schema = astToString(await openapiTS(document));
  const prettierOptions = {
    ...(await resolveConfig('src/api/schema.d.ts')),
    parser: 'typescript',
  };
  const output = await format(schema, {
    ...prettierOptions,
  });
  const policies = operationPolicies(document);
  const metadata = await format(
    '// Generated by scripts/gen-types.mjs from the same verified OpenAPI.\n' +
      `export const API_COMMIT = ${JSON.stringify(pin.commit)};\n` +
      `export const API_SCHEMA_SHA256 = ${JSON.stringify(pin.sha256)};\n` +
      `export const IDEMPOTENT_OPERATIONS = ${JSON.stringify(policies.idempotent)} as const;\n` +
      `export const UPLOAD_OPERATIONS = ${JSON.stringify(policies.uploads)} as const;\n`,
    prettierOptions,
  );
  await mkdir('src/api', { recursive: true });
  await writeFile('src/api/schema.d.ts', output);
  await writeFile('src/api/operations.generated.ts', metadata);
  console.info(
    `Tipos e políticas gerados da API ${pin.commit}; SHA-256 verificado.`,
  );
} catch (error) {
  console.error(
    'Não foi possível gerar os tipos. Confira a fonte OpenAPI e a conexão.',
    error.message,
  );
  process.exitCode = 1;
}
